name: Build_Release
on:
  # See the documentation for more intricate event dispatch here:
  # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
  push:
    branches:
    - "master"

jobs:
  push:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ipfs-mexport-builder
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository_owner }}/ipfs-mexport-builder
          dockerfile: Dockerfile.builder
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: kubo-mexport
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository_owner }}/kubo-mexport
          dockerfile: Dockerfile.kubo
          github_token: ${{ secrets.GITHUB_TOKEN }}
